### ISSUE TITLE
U2F: requireResidentKey

### ISSUE THREAD

**Issue by Derad6709** [keepkey/keepkey-firmware#265]
Can I switch on requireResidentKey for U2F in my KeepKey? 

You can debug this thing at https://webauthn.me/debugger, and it doesn't work at the moment. Is this a hardware or software limitation?

**Comment by reidrankin** [comment]
The limitation here is that discoverable (nee resident) credentials require the authenticator (i.e. the KeepKey) to store state information for each credential created, which we can't do due to lack of space in the storage area for user data.

If you can think of any creative ways to overcome this limitation, we'd love to hear about them!
