### ISSUE TITLE
Add support for Binance Smart Chain transactions (MyEtherWallet)

### ISSUE THREAD

**Issue by DJFliX** [keepkey/keepkey-firmware#305]
Hi! I wanted to transfer funds over the Binance Smart Chain using my KeepKey with MyEtherWallet. Unfortunately I have discovered that while MEW is able to see funds associated with my Ethereum address on the Binance Smart Chain it is not possible to sign a transaction with the KeepKey. 

```
Incompatible EIP155-based V 147 and chain id 1. See the Common parameter of the Transaction constructor to set the chain id.
```

![dqsrmv8l3y681](https://user-images.githubusercontent.com/5497269/147386578-bc8dcdc3-3c7b-49dd-8f4a-14c0fb9e2abc.png)
 
Is support for the Binance Smart Chain achievable for the KeepKey? I see tons of open PR's and no real presence from keepkey staff so I'm quite hesitant to spend time on any form of implementation unless there is some certainty that it will actually be merged (if it meets the code quality standards obviously).

**Comment by BitHighlander** [comment]
Hey @DJFliX
     Interesting, I didn't realize BSC tx format would need a special patch. I know onboard.js supports BSC so this would be useful. We would welcome a pr patching this. perhaps I'll take a look at getting some BSC reference TX's into https://github.com/shapeshift/hdwallet and we could backport into keepkey. 

Thanks for posting

**Comment by mrnerdhair** [comment]
Context: https://www.reddit.com/r/MyEtherWallet/comments/rllvmw/transaction_on_bsc_chain_fails_incompatible/

**Comment by mrnerdhair** [comment]
The KK's firmware [supports](https://github.com/keepkey/keepkey-firmware/blob/master/lib/firmware/ethereum.c#L627-L638) alternate chain IDs natively. I've been looking through the MEW code trying to figure out where this is coming from. I've found some similar issues (like [this](https://github.com/NomicFoundation/hardhat/blob/e822c45da49fa1717d42c4ba9993644e7550b2bc/docs/metamask-issue.md) and [this](https://github.com/trufflesuite/ganache/pull/532)), and I don't think the problem is with KK -- the error strings appear to be from the Ethereum RPC server and are indicating that the KK is signing with a chain ID of 147 (which it would do if told to, but that would be really strange given that BSC's chain ID is 56) but something's expecting a chain id of 1 (which is also definitely wrong for BSC).

I don't know what MEW's backend looks like, but maybe they have something misconfigured somewhere?

**Comment by DJFliX** [comment]
@mrnerdhair Thanks for chiming in! I've quoted your latest response in the reddit thread and I've asked if there is a way for me to provide debug logs so that someone from MEW can verify whether the interaction between MEW and the KeepKey is working as they expect. If there are further developments I'll mention them here as well.

**Comment by BitHighlander** [comment]
BSC is now fully supported in app.shapeshift.com. MEW issues should be issued on their repo.

**Comment by DJFliX** [comment]
Amazing, thanks a lot. I'll seek out my KeepKey and try it out soon!
