### ISSUE TITLE
Process to add new coins/tokens

### ISSUE THREAD

**Issue by jleni** [keepkey/keepkey-firmware#38]
The process to add support for new coins/tokens does not seem to be documented.

Are there any guidelines in place?

**Comment by Positivism** [comment]
Modify then build the firmware.

**Comment by keepkeyjon** [comment]
Our team is happy to review patches, and work with the community to add support for more coins. The general process would be to add support to `keepkey/device-protocol`, `keepkey/keepkey-firmware`, and `keepkey/python-keepkey`. Make sure all the tests still pass on `keepkey/python-keepkey`, and then submit PRs. We'll review them, and give feedback where appropriate.

On the client side, we'll need pointers to the appropriate Insight fork (or otherwise), and some time to stand up a node, as well as support in `keepkey/device-client`.
